name: CMS Vinculacion CI/CD

on:
  push:
    branches: [ "main", "feature/equipo4-backend" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # T-23: Stage Build para .NET (Backend)
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0' # Ajustado a tu versión de proyecto

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar Backend (Stage Build)
        run: dotnet build --configuration Release --no-restore