name: CMS Vinculacion CI/CD

on:
  push:
    branches: [ "devops-config-ci-cd" ]

jobs:
  # T-23: Compilación
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Compilar Backend
        run: dotnet build CMSVinculacion.Api --configuration Release

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar y Compilar Frontend
        run: |
          cd Cms-obstreticia
          npm install
          npm run build

  # T-24: Ejecución de Pruebas (Corregido)
  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Ejecutar Pruebas xUnit
        # Forzamos a que busque en la carpeta de pruebas
        run: dotnet test Backend.Tests/Backend.Tests.csproj --verbosity normal

  test-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Ejecutar Pruebas Angular
        run: |
          cd Cms-obstreticia
          npm install  # Aseguramos que las dependencias estén para los tests
          # npx permite usar el comando 'ng' sin instalarlo globalmente
          npx ng test --watch=false --browsers=ChromeHeadless --no-progress