name: CMS Vinculacion CI/CD

on:
  push:
    branches: [ "devops-config-ci-cd" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Compilar Backend
        # Apuntamos directamente a la CARPETA, no al archivo .sln
        # GitHub buscará el archivo .csproj dentro de esa carpeta automáticamente
        run: dotnet build CMSVinculacion.Api --configuration Release